### ISSUE TITLE
Installing scripts

### ISSUE THREAD

**Issue by kopi23** [t4saha/stellarium-snap#2]
Hi, after successfully testing my script in the Script Console I wanted to make it permanently available. I tried placing a myscript.ssc file with the contents in my /home/myuser/.stellarium/scripts directory. But after restarting Stellarium (0.21.3), I can't find it in the Scripts tab of the Configuration window. Should this be possible?

I posted the same question earlier over at https://github.com/Stellarium/stellarium/discussions/2231 and they forwarded me to you.

Thank you, kopi

**Comment by t4saha** [comment]
@kopi23  Snap package uses separate xdg structure. Use this :
`/home/myuser/snap/stellarium-daily/common/.stellarium/scripts`

**Comment by kopi23** [comment]
@t4saha thank you very much. works like a charm :)
